name = "QuantumPropagators"
uuid = "7bf12567-5742-4b91-a078-644e72a65fc1"
authors = ["Michael Goerz <mail@michaelgoerz.net>"]
version = "0.1.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
OffsetArrays = "1"
ProgressMeter = "1"
SpecialFunctions = "1"
StaticArrays = "1"
julia = "1.6"
