name = "QuantumPropagators"
uuid = "7bf12567-5742-4b91-a078-644e72a65fc1"
authors = ["Michael Goerz <mail@michaelgoerz.net>"]
version = "0.8.2+dev"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[weakdeps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extensions]
QuantumPropagatorsODEExt = "OrdinaryDiffEq"
QuantumPropagatorsRecursiveArrayToolsExt = "RecursiveArrayTools"
QuantumPropagatorsStaticArraysExt = "StaticArrays"

[compat]
OffsetArrays = "1"
OrdinaryDiffEq = "6.59"
ProgressMeter = "1"
Random = "1"
RecursiveArrayTools = "3.12"
SpecialFunctions = "1, 2"
StaticArrays = "1"
TimerOutputs = "0.5.23"
julia = "1.9"
